name: Super Duper Pooper Scooper
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ANSIBLE: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
